# Generated by Django 3.2.7 on 2023-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('credit_score', models.PositiveIntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pan_card', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
